services:
  - type: web
    name: overseas-project-tracker
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
